# Generated by Django 4.1.3 on 2023-03-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_gym_website_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym_website',
            name='message',
        ),
    ]
