# Generated by Django 4.1.3 on 2023-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_detail',
        ),
    ]
