# Generated by Django 4.1.3 on 2023-03-21 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Datasaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasave',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasave',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
    ]
